name: Bug Report
description: Report a bug in the Chrome plugin
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting a bug. Please fill out the sections below.

  - type: input
    id: version
    attributes:
      label: Plugin Version
      description: Which version of the Chrome plugin are you using?
      placeholder: "0.1.0"
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Area
      description: Which area is affected?
      options:
        - Generator (Go code generation)
        - Manifest (manifest.json)
        - Extension template (React/Vite)
        - Content scripts
        - Side panel
        - Service worker
        - Plugin contributions (views/tabs)
        - CLI (chrome:build command)
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the bug.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Run `make chrome-build`
        2. Load unpacked extension in Chrome
        3. See error...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: Include error messages or console output.
    validations:
      required: true

  - type: input
    id: chrome-version
    attributes:
      label: Chrome Version
      description: Which version of Chrome are you using?
      placeholder: "Chrome 124"

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - macOS
        - Linux
        - Windows
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or log output.
