name: Feature Request
description: Suggest a new feature for the Chrome plugin
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature. Please describe what you'd like to see.

  - type: dropdown
    id: type
    attributes:
      label: Request Type
      options:
        - New generator output
        - Extension UI improvement
        - Content script enhancement
        - Plugin contribution type
        - Build pipeline improvement
        - Chrome API integration
        - Other
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this feature solve?
      placeholder: When building Chrome extensions with Orchestra plugins, I often need to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
      placeholder: |
        Add a new generator that produces...
        Or add a new contribution type that...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered

  - type: dropdown
    id: willing
    attributes:
      label: Would you submit a PR?
      options:
        - "Yes"
        - "Yes, with guidance"
        - "No"
    validations:
      required: true
