package generator

import (
	"fmt"
	"sort"
	"strings"

	"github.com/orchestra-mcp/chrome/src/types"
)

// GenerateExtensionConfig produces TypeScript source for extension-config.ts.
func GenerateExtensionConfig(cfg types.ExtensionConfig) string {
	var b strings.Builder
	b.WriteString("// Auto-generated by orchestra/chrome plugin. Do not edit.\n\n")
	b.WriteString("export const extensionConfig = {\n")
	b.WriteString(fmt.Sprintf("  name: %q,\n", cfg.Name))
	b.WriteString(fmt.Sprintf("  description: %q,\n", cfg.Description))
	b.WriteString(fmt.Sprintf("  version: %q,\n", cfg.Version))
	b.WriteString(fmt.Sprintf("  apiUrl: %q,\n", cfg.ApiURL))
	b.WriteString("  plugins: {\n")

	// Sort plugin keys for deterministic output.
	keys := make([]string, 0, len(cfg.Plugins))
	for k := range cfg.Plugins {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		b.WriteString(fmt.Sprintf("    %q: %q,\n", k, cfg.Plugins[k]))
	}

	b.WriteString("  },\n")
	b.WriteString("} as const;\n\n")
	b.WriteString("export type ExtensionConfig = typeof extensionConfig;\n")
	return b.String()
}
